### ISSUE TITLE
Support NWBv2 files created by IPNWB

### ISSUE THREAD

**Issue by t-b** [hdmf-dev/hdmf-common-schema#4]
Branch: https://github.com/t-b/hdmf-common-schema/tree/use-text-as-encoding-for-dynamic-table-column-names

Good day ✨

When creating NWBv2 files from Igor Pro I'm facing a general problem with the text encoding. I can only write files with UTF8 encoded strings.

The easy fix would be the following change

```
$ git diff .
diff --git a/common/table.yaml b/common/table.yaml
index 49c8b6c..73a5ad3 100644
--- a/common/table.yaml
+++ b/common/table.yaml
@@ -87,7 +87,7 @@ groups:
     of usability.
   attributes:
   - name: colnames
-    dtype: ascii
+    dtype: text
     dims:
     - num_columns
     shape:
(base)
```

That would undo the change from https://github.com/NeurodataWithoutBorders/pynwb/commit/b0939429 but I don't know why that was done.

**Comment by oruebel** [comment]
Since ``text`` is a more general type than ``ascii`` I think this should be fine, i.e., I don't think changing this should cause backward compatibility issues.  However, I don't recall why it was changed to ascii. @ajtritt what was the reason for chaning colnames to ascii in https://github.com/NeurodataWithoutBorders/pynwb/commit/b0939429

**Comment by ajtritt** [comment]
> what was the reason for chaning colnames to ascii in

Because I thought HDF5 names had to be ascii.... but that's not true, they can be unicode

**Comment by t-b** [comment]
Thanks both, I'll prepare a PR then.
